functions:
  build:
    - command: git.get_project
      params:
        directory: src
    - command: subprocess.exec
      params:
        working_dir: src
        env:
          JAVA_HOME: /opt/java/jdk11
        binary: ./gradlew
        args:
          - install
  "run tests":
    - command: subprocess.exec
      params:
        working_dir: src
        env:
          JAVA_HOME: /opt/java/jdk11
          MLAB_DATA_API_TEST_PROD_KEY: ${MLAB_DATA_API_TEST_PROD_KEY}
          MLAB_DATA_API_TEST_CONFIG: ${MLAB_DATA_API_TEST_CONFIG}
        binary: ./gradlew
        args:
          - :cleanTest
          - :test

tasks:
- name: compile
  commands:
    - func: build
- name: test
  depends_on:
    - name: compile
  commands:
    - func: run tests

buildvariants:
- name: main
  display_name: main
  run_on:
    - rhel70-small
  tasks:
    - compile
    - test
