functions:
  "fetch source":
    - command: git.get_project
      params:
        directory: mlab-data-api/src
  "run tests":
    - command: subprocess.exec
      params:
        working_dir: mlab-data-api/src
        env:
          JAVA_HOME: /opt/java/jdk11
          MLAB_DATA_API_TEST_PROD_KEY: ${MLAB_DATA_API_TEST_PROD_KEY}
          MLAB_DATA_API_TEST_CONFIG: ${MLAB_DATA_API_TEST_CONFIG}
        binary: ./gradlew
        args:
          - install
          - test

tasks:
- name: test
  commands:
    - func: fetch source
    - func: run tests

buildvariants:
- name: test
  display_name: test
  run_on:
    - ubuntu1804
  tasks:
    - test
