functions:
  "run tests":
    - command: git.get_project
      params:
        directory: src
    - command: subprocess.exec
      params:
        working_dir: src
        env:
          JAVA_HOME: /opt/java/jdk11
          MLAB_DATA_API_TEST_PROD_KEY: ${MLAB_DATA_API_TEST_PROD_KEY}
          MLAB_DATA_API_TEST_CONFIG: ${MLAB_DATA_API_TEST_CONFIG}
        binary: ./gradlew
        args:
          - install
          - test
  "build docker image":
    - command: git.get_project
      params:
        directory: src
    - command: subprocess.exec
      params:
        working_dir: src
        binary: docker
        args:
          - build
          - -t
          - mlab-data-api
          - .

tasks:
- name: test
  commands:
    - func: run tests
- name: docker
  commands:
    - func: build docker image

buildvariants:
- name: main
  display_name: main
  run_on:
    - rhel70-small
  tasks:
    - test
    - docker
