functions:
  "fetch source":
    - command: git.get_project
      params:
        directory: mlab-data-api/src
  "run tests":
    - command: subprocess.exec
      params:
        working_dir: mlab-data-api/src
        env:
          JAVA_HOME: /opt/java/jdk11
          MLAB_DATA_API_TEST_PROD_KEY: ${MLAB_DATA_API_TEST_PROD_KEY}
          MLAB_DATA_API_TEST_CONFIG: ${MLAB_DATA_API_TEST_CONFIG}
        binary: ./gradlew
        args:
          - install
          - test
  "install aws cli":
    - command: shell.exec
      params:
        working_dir: mlab-data-api
        shell: bash
        script: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

tasks:
- name: test
  commands:
    - func: fetch source
    - func: run tests
- name: docker
  commands:
    - func: fetch source
    - func: install aws cli

buildvariants:
- name: test
  display_name: run tests
  run_on:
    - rhel76-small
  tasks:
    - test
- name: docker
  display_name: publish docker image
  run_on:
    - rhel76-small
  tasks:
    - docker
