functions:
  "fetch source":
    - command: git.get_project
      params:
        directory: mlab-data-api/src
  "run tests":
    - command: subprocess.exec
      params:
        working_dir: mlab-data-api/src
        env:
          JAVA_HOME: /opt/java/jdk11
          MLAB_DATA_API_TEST_PROD_KEY: ${MLAB_DATA_API_TEST_PROD_KEY}
          MLAB_DATA_API_TEST_CONFIG: ${MLAB_DATA_API_TEST_CONFIG}
        binary: ./gradlew
        args:
          - install
          - test
  "build docker image":
    - command: subprocess.exec
      params:
        working_dir: mlab-data-api/src
        binary: docker
        args:
          - build
          - -t
          - mlab-data-api
          - .

tasks:
- name: test
  commands:
    - func: fetch source
    - func: run tests
- name: docker
  commands:
    - func: fetch source
    - func: build docker image

buildvariants:
- name: test
  display_name: run tests
  run_on:
    - ubuntu1804
  tasks:
    - test
- name: docker
  display_name: publish docker image
  run_on:
    - ubuntu1804
  tasks:
    - docker
